// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANysYcd7T3D0IixDLnpAXMyM8Wj6MrUek',
    appId: '1:408077969338:web:78e2fe53a18fa022245f83',
    messagingSenderId: '408077969338',
    projectId: 'employee-cec79',
    authDomain: 'employee-cec79.firebaseapp.com',
    storageBucket: 'employee-cec79.appspot.com',
    measurementId: 'G-SQKH252M9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapsEk_k1Oqv5Ovf11GrbiiL-E7pWdnO0',
    appId: '1:408077969338:android:a9c062c863b3cc2a245f83',
    messagingSenderId: '408077969338',
    projectId: 'employee-cec79',
    storageBucket: 'employee-cec79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03aEgRStPWIUjvGPgFhfTto-dMIlRoZ8',
    appId: '1:408077969338:ios:e410ddd70a331215245f83',
    messagingSenderId: '408077969338',
    projectId: 'employee-cec79',
    storageBucket: 'employee-cec79.appspot.com',
    iosClientId: '408077969338-78q7b2akavkdabgjcdb5ukpsh6p3s30v.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB03aEgRStPWIUjvGPgFhfTto-dMIlRoZ8',
    appId: '1:408077969338:ios:84d012716c311ffe245f83',
    messagingSenderId: '408077969338',
    projectId: 'employee-cec79',
    storageBucket: 'employee-cec79.appspot.com',
    iosClientId: '408077969338-7llk4cht6n35mgd322itkopuc6t90mn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp.RunnerTests',
  );
}
